import type { NextPage } from 'next';
import Head from 'next/head';
import { Cards } from '../components/Cards';
import { CheckboxGroup } from '../components/CheckboxGroup';
import { IconButtons } from '../components/IconButtons';
import { RadioGroup } from '../components/RadioButtonGroup';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Startsida</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Accessibility</h1>
      <h2>Markup spelar roll</h2>
      <RadioGroup />
      <CheckboxGroup />
      <IconButtons />
      <Cards />
    </>
  );
};

export default Home;
